apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: warehousewarehousetessera
  namespace: warehouse-ns
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: warehousewarehousetessera
  chart:
    git: ssh://git@github.com/uyentranle/blockchain-automation-framework.git
    ref: develop
    path: platforms/quorum/charts/node_tessera  
  values:
    replicaCount: 1
    metadata:
      namespace: warehouse-ns
      labels:
    images:
      node: quorumengineering/quorum:2.1.1
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      tessera: quorumengineering/tessera:0.9.2
      busybox: busybox
      mysql: mysql/mysql-server:5.7
    node:
      name: warehouse
      consensus: raft
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      servicetype: ClusterIP
      ports:
        rpc: 8546
        raft: 50401
        tm: 9001
        quorum: 21000
        db: 3306
      dbname: demodb
      mysqluser: demouser
      mysqlpassword: password
    vault:
      address: http://192.168.1.107:8200
      secretprefix: secret/warehouse-ns/crypto/warehouse
      serviceaccountname: vault-auth
      keyname: quorum
      tm_keyname: transaction
      role: vault-role
      authpath: quorumwarehouse
    tessera:
      dburl: "jdbc:mysql://localhost:3306/demodb"
      dbusername: $username
      dbpassword: $password
      url: "https://localhost:9001"
      othernodes:
        - url: https://carrier.test.quorum.blockchaincloudpoc.com:8443
        - url: https://manufacturer.test.quorum.blockchaincloudpoc.com:8443
        - url: https://store.test.quorum.blockchaincloudpoc.com:8443
        - url: https://warehouse.test.quorum.blockchaincloudpoc.com:8443
      tls: "STRICT"
      trust: "TOFU"
    genesis: ewogICAgImFsbG9jIjogewogICAgICAgICIzMzM3NjRmZTMyYmUyOGExMjU1NTdhMzI5YzIwMDVjY2MzYzRmYzkxIjogewogICAgICAgICAgICAiYmFsYW5jZSI6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgogICAgICAgIH0sCiAgICAgICAgImY5ZTkzMDM3ZDc3ZDcxYjFmZGQ2MDZiNGUwMTM0YzRlMDNhMTQ5YTUiOiB7CiAgICAgICAgICAgICJiYWxhbmNlIjogIjEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiCiAgICAgICAgfSwKICAgICAgICAiZmZjNWM2YTg3MzYyZDUyYTNkYjFiYTdmMWUwN2MxNTU3ODNlMGY3ZCI6IHsKICAgICAgICAgICAgImJhbGFuY2UiOiAiMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKICAgICAgICB9CiAgICB9LAogICAgImNvaW5iYXNlIjogIjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsCiAgICAiY29uZmlnIjogewogICAgICAgICJieXphbnRpdW1CbG9jayI6IDEsCiAgICAgICAgImNoYWluSWQiOiAxMCwKICAgICAgICAiZWlwMTUwQmxvY2siOiAxLAogICAgICAgICJlaXAxNTBIYXNoIjogIjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsCiAgICAgICAgImVpcDE1NUJsb2NrIjogMCwKICAgICAgICAiZWlwMTU4QmxvY2siOiAxLAogICAgICAgICJpc1F1b3J1bSI6IHRydWUKICAgIH0sCiAgICAiZGlmZmljdWx0eSI6ICIweDAiLAogICAgImV4dHJhRGF0YSI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImdhc0xpbWl0IjogIjB4RTAwMDAwMDAiLAogICAgIm1peGhhc2giOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDY0NzU3MjYxNmM2NTc4NzM2NTY0NmM2NTc4IiwKICAgICJub25jZSI6ICIweDAiLAogICAgInBhcmVudEhhc2giOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwKICAgICJ0aW1lc3RhbXAiOiAiMHgwMCIKfQ==
    staticnodes:
      - enode://aa968a01d09f3f301e72b0caaa2bae37872f6270c5bd7d7d2768d0ffc158a0f4c3cf4a42c5c2d217c1372bcc535840732434277462e56c3e32be28c2c384c0fa@carrier.test.quorum.blockchaincloudpoc.com:15010?discport=0&raftport=15013
      - enode://ef2f785a4b02bef570ac4294a4c0600365d3726be4bacdfa5b6afd41d8ba454721546c7a0d44b7966345f62b3419237154c8481c631db9e393200772fb1be74a@manufacturer.test.quorum.blockchaincloudpoc.com:15020?discport=0&raftport=15023
      - enode://29732e9817b563ddf9579a2098b1dce465a3933c797d90af06ee5c96c2800ab8a8cc13fe38ae8f0b59583088b9173c79053b7d26ed858c60c4015a61b0badd57@warehouse.test.quorum.blockchaincloudpoc.com:15040?discport=0&raftport=15043
    proxy:
      provider: "ambassador"
      external_url: warehouse.test.quorum.blockchaincloudpoc.com
      portTM: 15042
      rpcport: 15041
      quorumport: 15040
  
      portRaft: 15043
    storage:
      storageclassname: minikubestorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
