apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    app: consortiumchain
    version: '1'
    {{- if eq $.Values.proxy.provider "ambassador" }}
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: TCPMapping
      name: {{ .Values.node.name }}-tcp
      port: {{ .Values.proxy.quorumport }}
      service: {{ .Values.node.name }}.{{ .Values.metadata.namespace }}:{{ .Values.node.ports.quorum }}
      ---
      apiVersion: ambassador/v1
      kind: TCPMapping
      name: {{ .Values.node.name }}-rpc
      port: {{ .Values.proxy.rpcport }}
      service: {{ .Values.node.name }}.{{ .Values.metadata.namespace }}:{{ .Values.node.ports.rpc }}
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: {{ .Values.node.name }}-tm      
      host: {{ .Values.proxy.external_url }}:{{ .Values.proxy.portTM }}
      prefix: /
      host_rewrite: {{ .Values.node.name }}-0.{{ .Values.node.name }}.{{ .Values.metadata.namespace }}.svc.cluster.local
      service: https://{{ .Values.node.name }}.{{ .Values.metadata.namespace }}:{{ .Values.node.ports.tm }}
      tls: {{ .Values.node.name }}_mapping_tlscontext
      ---
      apiVersion: ambassador/v1
      kind: TLSContext
      name: {{ .Values.node.name }}_mapping_tlscontext
      hosts:
      - {{ .Values.proxy.external_url }}
      secret: {{ .Values.node.name }}-ambassador-certs
      {{- if eq $.Values.node.consensus "raft" }}
      ---
      apiVersion: ambassador/v1
      kind: TCPMapping
      name: {{ .Values.node.name }}-raft
      port: {{ .Values.proxy.portRaft }}
      service: {{ .Values.node.name }}.{{ .Values.metadata.namespace }}:{{ .Values.node.ports.raft }}
      {{- end }}
    {{- end }}
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: {{ .Values.node.name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }} 
    {{- include "labels.custom" . | nindent 2 }}
  name: {{ .Values.node.name }}
spec:
{{- if eq .Values.cloudprovider "minikube" }}
  type: NodePort
{{- else }}
  type: ClusterIP
{{- end }}
  ports:
  - name: wsrpc-listener
    protocol: TCP
    port: {{ .Values.node.ports.rpc }}
    targetPort: {{ .Values.node.ports.rpc }}
{{- if eq $.Values.node.consensus "raft" }}
  - name: raft
    protocol: TCP
    port: {{ .Values.node.ports.raft }}
    targetPort: {{ .Values.node.ports.raft }}
{{- end }}
  - name: tm-manager
    protocol: TCP
    port: {{ .Values.node.ports.tm }}
    targetPort: {{ .Values.node.ports.tm }}
  - name: quorum-listener
    protocol: TCP
    port: {{ .Values.node.ports.quorum }}
    targetPort: {{ .Values.node.ports.quorum }}
  - name: tm-tessera-third-part
    protocol: TCP
    port: 9080
    targetPort: 9080
  selector:
    service.rpc: {{ .Values.node.name }}
